import React, { createContext, useState } from "react";


export const productContext = createContext(null);


const ProductContext = ({ children }) => {
  const [products, setProducts] = useState([
  {
    id: 9,
    name: "The Hustle-Bhasad Hoodie 21",
    price: 1099,
    image: "/images/hood4.jpg",
    description: "Iconic black hoodie with BB's Bancho punchline.",
    category: "Hoodies",
    inStock: true,
    slug: "bb-bancho-black",
    tags: ["bb", "bancho", "black", "bold"],
  },
  {
    id: 16,
    name: "Bancho Edition Red",
    price: 349,
    image: "/images/mug4.jpg",
    hoverImage: "/images/mug44.png",
    description: "Official BB merchandise ceramic mug with brand logo.",
    category: "Funky Mugs",
    inStock: true,
    slug: "bb-logo-mug",
    tags: ["bb", "logo", "merch", "mug"],
  },
  {
    id: 1,
    name: "The Hustle Bhasad Tee - Maroon",
    price: 549,
    image: "/images/HustleMaroon.jpg",
    hoverImage: "/images/Maroom.png",
    description:
      "Oversized washed maroon tee with bold 'Hustle Bhasad' typography.",
    category: "T-Shirts",
    inStock: true,
    slug: "hustle-bhasad-maroon",
    tags: ["hustle", "oversized", "typography", "streetwear"],
  },
  {
    id: 11,
    name: "DTYDHTB Hoodie",
    price: 899,
    image: "/images/hood6.jpg",
    description: "Grey hoodie for deep thinkers. Minimal, clean design.",
    category: "Hoodies",
    inStock: true,
    slug: "overthinker-grey",
    tags: ["minimal", "grey", "casual", "hoodie"],
  },
  {
    id: 5,
    name: "Singh Nahi Hote Edition",
    price: 549,
    image: "/images/singh1.jpg",
    hoverImage: "/images/singh.jpg",
    description:
      "Sky blue tee perfect for your off-days. Chill. Comfy. Clean.",
    category: "T-Shirts",
    inStock: true,
    slug: "weekend-vibes-sky-blue",
    tags: ["weekend", "casual", "chill", "sky blue"],
  },
  {
    id: 18,
    name: "BB Strange Limited Edition",
    price: 525,
    image: "/images/mug6.jpg",
    hoverImage: "/images/mug66.jpg",
    description: "Colorful ceramic mug with bold Youthiapa typography.",
    category: "Funky Mugs",
    inStock: true,
    slug: "youthiapa-funky-mug",
    tags: ["youthiapa", "colorful", "funky", "mug"],
  },
  {
    id: 8,
    name: "Relax Edition Zipper Hoodie",
    price: 949,
    image: "/images/hood3.jpg",
    description: "Comfy white hoodie with 'No Chill' quote on front.",
    category: "Hoodies",
    inStock: true,
    slug: "no-chill-white",
    tags: ["hoodie", "white", "funny", "casual"],
  },
  {
    id: 3,
    name: "Dialogue Bazi Edition_Black",
    price: 549,
    image: "/images/dialouge.jpg",
    hoverImage: "/images/4Q5A6794_copy.jpg",
    description:
      "Classic white tee with Youthiapa core logo in minimalist style.",
    category: "T-Shirts",
    inStock: true,
    slug: "youthiapa-core-logo-white",
    tags: ["core", "minimal", "logo", "white"],
  },
  {
    id: 13,
    name: "Bancho Edition Mug ",
    price: 299,
    image: "/images/mug1.jpg",
    hoverImage: "/images/mug11.png",
    description: "Classic white ceramic mug with 'Bancho' printed bold.",
    category: "Funky Mugs",
    inStock: true,
    slug: "bancho-mug-white",
    tags: ["mug", "white", "bancho", "funny"],
  },
  {
    id: 7,
    name: "Oh Yeah Hoodie",
    price: 999,
    image: "/images/hood1.jpg",
    hoverImage: "/images/hood2.png",
    description: "Bold black hoodie with Winter Soldier arm print.",
    category: "Hoodies",
    inStock: true,
    slug: "winter-soldier-black",
    tags: ["hoodie", "black", "winter", "marvel"],
  },
  {
    id: 15,
    name: "Oh Yeah Sameer Edition",
    price: 319,
    image: "/images/mug3.jpg",
    hoverImage: "/images/mug33.png",
    description:
      "'No Filter' printed funky mug for your unfiltered mornings.",
    category: "Funky Mugs",
    inStock: true,
    slug: "no-filter-mug",
    tags: ["mug", "bold", "quote", "funny"],
  },
  {
    id: 14,
    name: "Sahi Khel Gaya Bancho Edition ",
    price: 329,
    image: "/images/mug2.jpg",
    hoverImage: "/images/mug22.png",
    description: "Black coffee mug with red 'Dil Se' heart logo.",
    category: "Funky Mugs",
    inStock: true,
    slug: "dil-se-mug-black",
    tags: ["mug", "black", "heart", "romantic"],
  },
  {
    id: 2,
    name: "The Hustle Bhasad Tee - Pink",
    price: 599,
    image: "/images/HustlePink.jpg",
    hoverImage: "/images/Pink.png",
    description:
      "Oversized washed black tee with floral print and 'Raised Right' graphic.",
    category: "T-Shirts",
    inStock: true,
    slug: "raised-right-floral-black",
    tags: ["raised right", "floral", "black", "oversized"],
  },
  {
    id: 6,
    name: "Bancho Izzat Edition - Black",
    price: 549,
    image: "/images/IzzatBlack.jpg",
    hoverImage: "/images/IzzatBlack2.jpg",
    description:
      "Raw and real—charcoal tee with 'No Filter' stitched detail.",
    category: "T-Shirts",
    inStock: true,
    slug: "no-filter-charcoal",
    tags: ["no filter", "real", "street", "charcoal"],
  },
  {
    id: 17,
    name: "Heer Ranjha Limited Edition",
    price: 525,
    image: "/images/mug5.jpg",
    hoverImage: "/images/mug55.jpg",
    description: "Witty mug with 'Sarcasm Loading...' design.",
    category: "Funky Mugs",
    inStock: true,
    slug: "sarcasm-loading-mug",
    tags: ["funny", "sarcasm", "mug", "quote"],
  },
  {
    id: 12,
    name: "Dhindora Official Hoodie",
    price: 949,
    image: "/images/hood7.jpg",
    description: "Bright red hoodie with 'Dil Se' heart print in front.",
    category: "Hoodies",
    inStock: true,
    slug: "dil-se-red",
    tags: ["dil se", "red", "heart", "love", "hoodie"],
  },
  {
    id: 4,
    name: "Bancho Black Edition",
    price: 549,
    image: "/images/khelgaya.jpg",
    hoverImage: "/images/khelgayabancho.jpg",
    description:
      "Olive green tee with bold 'Bad Decisions Make Good Stories' slogan.",
    category: "T-Shirts",
    inStock: true,
    slug: "bad-decisions-olive-green",
    tags: ["slogan", "oversized", "green", "bold"],
  },
  {
    id: 10,
    name: "Young by Youthiapa Hoodie",
    price: 999,
    image: "/images/hood5.jpg",
    description: "Maroon hoodie with embroidered Youthiapa logo.",
    category: "Hoodies",
    inStock: true,
    slug: "youthiapa-maroon",
    tags: ["youthiapa", "maroon", "embroidered", "hoodie"],
  },
]);


  return (
    <productContext.Provider value={{ products, setProducts }}>
      {children}
    </productContext.Provider>
  );
};

export default ProductContext;
